package com.transport.erp.service;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.transport.erp.exception.BusinessValidationException;
import com.transport.erp.model.AppUser;
import com.transport.erp.repository.CompanyRepository;
import com.transport.erp.security.TenantAccessService;
import jakarta.annotation.PostConstruct;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.InputStream;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.*;

/**
 * Reports hub. Every report is a read-only SQL query defined in reports/report-catalog.json
 * (generated by tools/reports/generate_catalog.py and checked against the real schema by
 * tools/reports/test_catalog_sql.py). The service scopes each run to the user's company (and branch
 * for branch-bound users), applies the filters, adds column totals and renders JSON / Excel / PDF.
 */
@Service
public class ReportHubService {

    public static final int MAX_SCREEN_ROWS = 5000;
    public static final int MAX_EXPORT_ROWS = 50000;
    private static final Set<String> FINANCE_ROLES = Set.of("ROLE_SUPER_ADMIN", "ROLE_COMPANY_ADMIN", "ROLE_ADMIN",
            "ROLE_ACCOUNTANT", "ROLE_BRANCH_MANAGER", "ROLE_VIEWER");
    private static final DateTimeFormatter D = DateTimeFormatter.ofPattern("dd-MM-yyyy");

    @Autowired private NamedParameterJdbcTemplate jdbc;
    @Autowired private TenantAccessService tenantAccess;
    @Autowired private CompanyRepository companyRepository;
    @Autowired private XlsxExportService xlsx;
    @Autowired private ObjectMapper objectMapper;

    private List<Map<String, Object>> catalog = List.of();
    private final Map<String, Map<String, Object>> byKey = new LinkedHashMap<>();

    @PostConstruct
    void load() throws Exception {
        try (InputStream in = new ClassPathResource("reports/report-catalog.json").getInputStream()) {
            catalog = objectMapper.readValue(in, new TypeReference<List<Map<String, Object>>>() { });
        }
        for (Map<String, Object> r : catalog) byKey.put((String) r.get("key"), r);
    }

    /** Reports this user may run (no SQL). */
    public List<Map<String, Object>> catalog() {
        boolean finance = hasFinanceRole();
        List<Map<String, Object>> out = new ArrayList<>();
        for (Map<String, Object> r : catalog) {
            if (Boolean.TRUE.equals(r.get("finance")) && !finance) continue;
            Map<String, Object> m = new LinkedHashMap<>(r);
            m.remove("sql");
            out.add(m);
        }
        return out;
    }

    public record Result(Map<String, Object> report, Map<String, Object> filters, List<Map<String, Object>> columns,
                         List<Map<String, Object>> rows, Map<String, Object> totals, int rowCount, boolean truncated) { }

    @Transactional(readOnly = true)
    public Result run(String key, Map<String, String> params, int maxRows) {
        Map<String, Object> def = byKey.get(key);
        if (def == null) {
            throw new BusinessValidationException("Report Not Found", "REPORT_NOT_FOUND", "Unknown report: " + key, "Pick a report from the list.");
        }
        if (Boolean.TRUE.equals(def.get("finance")) && !hasFinanceRole()) {
            throw new AccessDeniedException("This report needs an accounts or admin role.");
        }
        MapSqlParameterSource p = new MapSqlParameterSource();
        Map<String, Object> applied = new LinkedHashMap<>();

        Long companyId = tenantAccess.resolveCompanyId(parseLong(params.get("companyId")));
        p.addValue("companyId", companyId);

        LocalDate to = parseDate(params.get("to"), LocalDate.now());
        LocalDate from = parseDate(params.get("from"), to.withDayOfMonth(1));
        if (from.isAfter(to)) {
            throw new BusinessValidationException("Invalid Period", "REPORT_PERIOD_INVALID", "From date is after To date.", "Correct the dates.");
        }
        if (ChronoUnit.DAYS.between(from, to) > 3 * 366) {
            throw new BusinessValidationException("Period Too Long", "REPORT_PERIOD_TOO_LONG", "Reports cover at most 3 years.", "Choose a shorter period.");
        }
        p.addValue("from", from.toString());
        p.addValue("to", to.toString());
        applied.put("from", from.toString());
        applied.put("to", to.toString());

        // Branch-bound users only ever see their own branch.
        Long branch = parseLong(params.get("branchId"));
        Long restricted = restrictedBranchId();
        if (restricted != null) branch = restricted;
        p.addValue("branchId", branch);
        if (branch != null) applied.put("branchId", branch);

        for (String k : List.of("vehicleId", "driverId", "customerId", "warehouseId", "sparePartId")) {
            Long v = parseLong(params.get(k));
            p.addValue(k, v);
            if (v != null) applied.put(k, v);
        }
        Integer days = params.get("days") == null || params.get("days").isBlank() ? null : Integer.valueOf(params.get("days").trim());
        p.addValue("days", days);
        for (String k : List.of("status", "category", "accountCode")) {
            String v = params.get(k) == null || params.get(k).isBlank() ? null : params.get(k).trim().toUpperCase();
            if ("accountCode".equals(k) && v != null) v = params.get(k).trim();
            p.addValue(k, v);
            if (v != null) applied.put(k, v);
        }

        String sql = "SELECT * FROM (" + def.get("sql") + ") report_rows LIMIT " + (maxRows + 1);
        List<Map<String, Object>> raw = jdbc.queryForList(sql, p);
        boolean truncated = raw.size() > maxRows;
        if (truncated) raw = raw.subList(0, maxRows);

        @SuppressWarnings("unchecked")
        List<Map<String, Object>> columns = (List<Map<String, Object>>) def.get("columns");
        List<Map<String, Object>> rows = new ArrayList<>(raw.size());
        Map<String, BigDecimal> sums = new LinkedHashMap<>();
        for (Map<String, Object> r : raw) {
            Map<String, Object> row = new LinkedHashMap<>();
            for (Map<String, Object> c : columns) {
                String ck = (String) c.get("key");
                Object v = r.get(ck);
                if (v instanceof java.sql.Date d) v = d.toLocalDate().toString();
                if (v instanceof java.sql.Timestamp ts) v = ts.toLocalDateTime().toString();
                row.put(ck, v);
                if (Boolean.TRUE.equals(c.get("total")) && v instanceof Number n) {
                    sums.merge(ck, new BigDecimal(n.toString()), BigDecimal::add);
                }
            }
            rows.add(row);
        }
        Map<String, Object> totals = new LinkedHashMap<>();
        for (Map<String, Object> c : columns) {
            if (Boolean.TRUE.equals(c.get("total"))) totals.put((String) c.get("key"), sums.getOrDefault((String) c.get("key"), BigDecimal.ZERO));
        }
        Map<String, Object> meta = new LinkedHashMap<>(def);
        meta.remove("sql");
        return new Result(meta, applied, columns, rows, totals, rows.size(), truncated);
    }

    @Transactional(readOnly = true)
    public byte[] export(String key, Map<String, String> params, String format) {
        Result r = run(key, params, MAX_EXPORT_ROWS);
        String[] headers = r.columns().stream().map(c -> (String) c.get("label")).toArray(String[]::new);
        List<Object[]> rows = new ArrayList<>();
        for (Map<String, Object> row : r.rows()) {
            Object[] arr = new Object[headers.length];
            int i = 0;
            for (Map<String, Object> c : r.columns()) {
                Object v = row.get((String) c.get("key"));
                if (v instanceof String s && "date".equals(c.get("type")) && s.length() >= 10) {
                    try { v = LocalDate.parse(s.substring(0, 10)); } catch (Exception ignored) { }
                }
                arr[i++] = v;
            }
            rows.add(arr);
        }
        if (!r.totals().isEmpty() && !rows.isEmpty()) {
            Object[] tot = new Object[headers.length];
            int i = 0;
            for (Map<String, Object> c : r.columns()) {
                tot[i] = r.totals().get((String) c.get("key"));
                i++;
            }
            if (tot[0] == null) tot[0] = "TOTAL";
            rows.add(tot);
        }
        String title = (String) r.report().get("title");
        if ("pdf".equalsIgnoreCase(format)) {
            return com.transport.erp.util.TablePdfGenerator.render(title, companyName(), describe(r.filters()), headers, rows);
        }
        return xlsx.buildExcelWorkbook(title.length() > 31 ? title.substring(0, 31) : title, headers, rows);
    }

    private String describe(Map<String, Object> f) {
        StringBuilder sb = new StringBuilder();
        if (f.get("from") != null) {
            sb.append(LocalDate.parse((String) f.get("from")).format(D)).append(" to ").append(LocalDate.parse((String) f.get("to")).format(D));
        }
        f.forEach((k, v) -> { if (!"from".equals(k) && !"to".equals(k)) sb.append(" · ").append(k).append(": ").append(v); });
        return sb.toString();
    }

    private String companyName() {
        try {
            return companyRepository.findById(tenantAccess.resolveCompanyId(null)).map(c -> c.getName()).orElse("");
        } catch (Exception e) {
            return "";
        }
    }

    private boolean hasFinanceRole() {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        return auth != null && auth.getAuthorities().stream().anyMatch(a -> FINANCE_ROLES.contains(a.getAuthority()));
    }

    private Long restrictedBranchId() {
        AppUser user = tenantAccess.requireCurrentUser();
        if (tenantAccess.isSuperAdmin(user)) return null;
        boolean companyWide = user.getRoles() != null && user.getRoles().stream()
                .anyMatch(r -> "COMPANY_ADMIN".equals(r.getCode()) || "ADMIN".equals(r.getCode()) || "ACCOUNTANT".equals(r.getCode()) || "VIEWER".equals(r.getCode()));
        return companyWide ? null : user.getBranchId();
    }

    private static Long parseLong(String s) {
        if (s == null || s.isBlank() || "null".equalsIgnoreCase(s)) return null;
        try { return Long.valueOf(s.trim()); } catch (NumberFormatException e) {
            throw new BusinessValidationException("Invalid Filter", "REPORT_FILTER_INVALID", "Filter value '" + s + "' is not a number.", "Pick the value from the list.");
        }
    }

    private static LocalDate parseDate(String s, LocalDate def) {
        if (s == null || s.isBlank()) return def;
        try { return LocalDate.parse(s.trim()); } catch (Exception e) {
            throw new BusinessValidationException("Invalid Date", "REPORT_DATE_INVALID", "Date '" + s + "' is not valid (use YYYY-MM-DD).", "Pick the date again.");
        }
    }
}
