-- 005_lookups.sql — master dropdowns / statuses / types
INSERT INTO lookup_values (type, code, name, description, status, company_id, created_by) VALUES
 ('BOOKING_STATUS','DRAFT','Draft','Draft','ACTIVE',1,'SYSTEM'),
 ('BOOKING_STATUS','PENDING','Pending','Pending','ACTIVE',1,'SYSTEM'),
 ('BOOKING_STATUS','APPROVED','Approved','Approved','ACTIVE',1,'SYSTEM'),
 ('BOOKING_STATUS','IN_PROGRESS','In Progress','In progress','ACTIVE',1,'SYSTEM'),
 ('BOOKING_STATUS','COMPLETED','Completed','Completed','ACTIVE',1,'SYSTEM'),
 ('BOOKING_STATUS','CANCELLED','Cancelled','Cancelled','ACTIVE',1,'SYSTEM'),
 ('BOOKING_STATUS','ON_HOLD','On Hold','On hold','ACTIVE',1,'SYSTEM'),
 ('BOOKING_STATUS','REJECTED','Rejected','Rejected','ACTIVE',1,'SYSTEM'),
 ('TRIP_STATUS','PLANNED','Planned','Planned','ACTIVE',1,'SYSTEM'),
 ('TRIP_STATUS','ALLOCATED','Allocated','Allocated','ACTIVE',1,'SYSTEM'),
 ('TRIP_STATUS','LOADING','Loading','Loading','ACTIVE',1,'SYSTEM'),
 ('TRIP_STATUS','LOADED','Loaded','Loaded','ACTIVE',1,'SYSTEM'),
 ('TRIP_STATUS','DISPATCHED','Dispatched','Dispatched','ACTIVE',1,'SYSTEM'),
 ('TRIP_STATUS','IN_TRANSIT','In Transit','In transit','ACTIVE',1,'SYSTEM'),
 ('TRIP_STATUS','ARRIVED','Arrived','Arrived','ACTIVE',1,'SYSTEM'),
 ('TRIP_STATUS','UNLOADING','Unloading','Unloading','ACTIVE',1,'SYSTEM'),
 ('TRIP_STATUS','DELIVERED','Delivered','Delivered','ACTIVE',1,'SYSTEM'),
 ('TRIP_STATUS','COMPLETED','Completed','Completed','ACTIVE',1,'SYSTEM'),
 ('TRIP_STATUS','CANCELLED','Cancelled','Cancelled','ACTIVE',1,'SYSTEM'),
 ('INVOICE_STATUS','DRAFT','Draft','Draft','ACTIVE',1,'SYSTEM'),
 ('INVOICE_STATUS','PENDING','Pending','Pending','ACTIVE',1,'SYSTEM'),
 ('INVOICE_STATUS','APPROVED','Approved','Approved','ACTIVE',1,'SYSTEM'),
 ('INVOICE_STATUS','GENERATED','Generated','Generated','ACTIVE',1,'SYSTEM'),
 ('INVOICE_STATUS','PAID','Paid','Paid','ACTIVE',1,'SYSTEM'),
 ('INVOICE_STATUS','CANCELLED','Cancelled','Cancelled','ACTIVE',1,'SYSTEM'),
 ('EXPENSE_STATUS','DRAFT','Draft','Draft','ACTIVE',1,'SYSTEM'),
 ('EXPENSE_STATUS','SUBMITTED','Submitted','Submitted','ACTIVE',1,'SYSTEM'),
 ('EXPENSE_STATUS','APPROVED','Approved','Approved','ACTIVE',1,'SYSTEM'),
 ('EXPENSE_STATUS','REJECTED','Rejected','Rejected','ACTIVE',1,'SYSTEM'),
 ('EXPENSE_STATUS','PAID','Paid','Paid','ACTIVE',1,'SYSTEM'),
 ('EXPENSE_STATUS','CANCELLED','Cancelled','Cancelled','ACTIVE',1,'SYSTEM'),
 ('FUEL_REQUEST_STATUS','PENDING','Pending','Pending','ACTIVE',1,'SYSTEM'),
 ('FUEL_REQUEST_STATUS','APPROVED','Approved','Approved','ACTIVE',1,'SYSTEM'),
 ('FUEL_REQUEST_STATUS','REJECTED','Rejected','Rejected','ACTIVE',1,'SYSTEM'),
 ('VEHICLE_STATUS','AVAILABLE','Available','Available','ACTIVE',1,'SYSTEM'),
 ('VEHICLE_STATUS','ON_TRIP','On Trip','On trip','ACTIVE',1,'SYSTEM'),
 ('VEHICLE_STATUS','UNDER_MAINTENANCE','Under Maintenance','Workshop','ACTIVE',1,'SYSTEM'),
 ('VEHICLE_STATUS','IDLE','Idle','Idle','ACTIVE',1,'SYSTEM'),
 ('VEHICLE_STATUS','INACTIVE','Inactive','Inactive','ACTIVE',1,'SYSTEM'),
 ('DRIVER_STATUS','AVAILABLE','Available','Available','ACTIVE',1,'SYSTEM'),
 ('DRIVER_STATUS','ON_TRIP','On Trip','On trip','ACTIVE',1,'SYSTEM'),
 ('DRIVER_STATUS','ON_LEAVE','On Leave','Leave','ACTIVE',1,'SYSTEM'),
 ('DRIVER_STATUS','INACTIVE','Inactive','Inactive','ACTIVE',1,'SYSTEM'),
 ('STATUS','ACTIVE','Active','Active','ACTIVE',1,'SYSTEM'),
 ('STATUS','INACTIVE','Inactive','Inactive','ACTIVE',1,'SYSTEM'),
 ('VEHICLE_TYPE','TIPPER','Tipper Lorry','Tipper','ACTIVE',1,'SYSTEM'),
 ('VEHICLE_TYPE','JCB','JCB / Excavator','JCB','ACTIVE',1,'SYSTEM'),
 ('VEHICLE_CATEGORY','HEAVY','Heavy Commercial Vehicle','HCV','ACTIVE',1,'SYSTEM'),
 ('VEHICLE_CATEGORY','EQUIPMENT','Construction Equipment','Equipment','ACTIVE',1,'SYSTEM'),
 ('VEHICLE_CAPACITY','16_TON','16 Ton','16T','ACTIVE',1,'SYSTEM'),
 ('VEHICLE_CAPACITY','18_TON','18 Ton','18T','ACTIVE',1,'SYSTEM'),
 ('VEHICLE_CAPACITY','20_TON','20 Ton','20T','ACTIVE',1,'SYSTEM'),
 ('VEHICLE_CAPACITY','JCB_STD','JCB Standard','JCB','ACTIVE',1,'SYSTEM'),
 ('MATERIAL_CATEGORY','SAND','Sand','Sand','ACTIVE',1,'SYSTEM'),
 ('MATERIAL_CATEGORY','AGGREGATE','Aggregate / Jalli','Aggregate','ACTIVE',1,'SYSTEM'),
 ('MATERIAL_CATEGORY','DUST','Crusher Dust','Dust','ACTIVE',1,'SYSTEM'),
 ('MATERIAL_CATEGORY','WMM','Wet Mix / Gravel','WMM','ACTIVE',1,'SYSTEM'),
 ('MATERIAL_UNIT','TON','Ton','MT','ACTIVE',1,'SYSTEM'),
 ('MATERIAL_UNIT','LOAD','Load','Load','ACTIVE',1,'SYSTEM'),
 ('MATERIAL_UNIT','CUBIC_METER','Cubic Meter','Cum','ACTIVE',1,'SYSTEM'),
 ('FUEL_TYPE','DIESEL','Diesel','HSD','ACTIVE',1,'SYSTEM'),
 ('FUEL_TYPE','PETROL','Petrol','Petrol','ACTIVE',1,'SYSTEM'),
 ('EXPENSE_TYPE','DRIVER_BATA','Driver Bata','Bata','ACTIVE',1,'SYSTEM'),
 ('EXPENSE_TYPE','TOLL','Toll','Toll','ACTIVE',1,'SYSTEM'),
 ('EXPENSE_TYPE','PARKING','Parking','Parking','ACTIVE',1,'SYSTEM'),
 ('EXPENSE_TYPE','VEHICLE_REPAIR','Vehicle Repair','Repair','ACTIVE',1,'SYSTEM'),
 ('EXPENSE_TYPE','VEHICLE_SERVICE','Vehicle Service','Service','ACTIVE',1,'SYSTEM'),
 ('EXPENSE_TYPE','TYRE','Tyre','Tyre','ACTIVE',1,'SYSTEM'),
 ('EXPENSE_TYPE','LOADING','Loading Charges','Loading','ACTIVE',1,'SYSTEM'),
 ('EXPENSE_TYPE','MISCELLANEOUS','Miscellaneous','Misc','ACTIVE',1,'SYSTEM'),
 ('PAYMENT_METHOD','CASH','Cash','Cash','ACTIVE',1,'SYSTEM'),
 ('PAYMENT_METHOD','UPI','UPI','UPI','ACTIVE',1,'SYSTEM'),
 ('PAYMENT_METHOD','NEFT','NEFT','NEFT','ACTIVE',1,'SYSTEM'),
 ('PAYMENT_METHOD','RTGS','RTGS','RTGS','ACTIVE',1,'SYSTEM'),
 ('PAYMENT_METHOD','IMPS','IMPS','IMPS','ACTIVE',1,'SYSTEM'),
 ('PAYMENT_METHOD','BANK_TRANSFER','Bank Transfer','Bank','ACTIVE',1,'SYSTEM'),
 ('PAYMENT_METHOD','CHEQUE','Cheque','Cheque','ACTIVE',1,'SYSTEM'),
 ('PAYMENT_METHOD','CREDIT','Credit','Credit','ACTIVE',1,'SYSTEM'),
 ('PRIORITY','HIGH','High','High','ACTIVE',1,'SYSTEM'),
 ('PRIORITY','MEDIUM','Medium','Medium','ACTIVE',1,'SYSTEM'),
 ('PRIORITY','LOW','Low','Low','ACTIVE',1,'SYSTEM'),
 ('PAYMENT_TERMS','IMMEDIATE','Due on Receipt','Immediate','ACTIVE',1,'SYSTEM'),
 ('PAYMENT_TERMS','NET_7','Net 7 Days','7d','ACTIVE',1,'SYSTEM'),
 ('PAYMENT_TERMS','NET_15','Net 15 Days','15d','ACTIVE',1,'SYSTEM'),
 ('PAYMENT_TERMS','NET_30','Net 30 Days','30d','ACTIVE',1,'SYSTEM'),
 ('CURRENCY','INR','Indian Rupee','INR','ACTIVE',1,'SYSTEM'),
 ('GST_RATE','GST_0','0%','Nil','ACTIVE',1,'SYSTEM'),
 ('GST_RATE','GST_5','5%','5','ACTIVE',1,'SYSTEM'),
 ('GST_RATE','GST_12','12%','12','ACTIVE',1,'SYSTEM'),
 ('GST_RATE','GST_18','18%','18','ACTIVE',1,'SYSTEM'),
 ('VEHICLE_DOCUMENT_TYPE','INSURANCE','Insurance','Insurance','ACTIVE',1,'SYSTEM'),
 ('VEHICLE_DOCUMENT_TYPE','PERMIT','Permit','Permit','ACTIVE',1,'SYSTEM'),
 ('VEHICLE_DOCUMENT_TYPE','FITNESS','Fitness','Fitness','ACTIVE',1,'SYSTEM'),
 ('VEHICLE_DOCUMENT_TYPE','PUC','PUC','PUC','ACTIVE',1,'SYSTEM'),
 ('VEHICLE_DOCUMENT_TYPE','RC','RC Book','RC','ACTIVE',1,'SYSTEM'),
 ('DRIVER_DOCUMENT_TYPE','LICENSE_SCAN','Driving License','DL','ACTIVE',1,'SYSTEM'),
 ('DRIVER_DOCUMENT_TYPE','AADHAAR','Aadhaar','Aadhaar','ACTIVE',1,'SYSTEM'),
 ('DRIVER_DOCUMENT_TYPE','PAN','PAN','PAN','ACTIVE',1,'SYSTEM'),
 ('CUSTOMER_DOCUMENT_TYPE','GST_CERT','GST Certificate','GST','ACTIVE',1,'SYSTEM'),
 ('CUSTOMER_DOCUMENT_TYPE','PAN_CARD','PAN Card','PAN','ACTIVE',1,'SYSTEM'),
 ('MAINTENANCE_TYPE','OIL_CHANGE','Oil Change','Oil','ACTIVE',1,'SYSTEM'),
 ('MAINTENANCE_TYPE','ENGINE_SERVICE','Engine Service','Engine','ACTIVE',1,'SYSTEM'),
 ('MAINTENANCE_TYPE','TYRE_CHANGE','Tyre Change','Tyre','ACTIVE',1,'SYSTEM'),
 ('MAINTENANCE_TYPE','BRAKE_SERVICE','Brake Service','Brake','ACTIVE',1,'SYSTEM'),
 ('MAINTENANCE_TYPE','GENERAL_SERVICE','General Service','General','ACTIVE',1,'SYSTEM'),
 ('ATTENDANCE_STATUS','PRESENT','Present','Present','ACTIVE',1,'SYSTEM'),
 ('ATTENDANCE_STATUS','ABSENT','Absent','Absent','ACTIVE',1,'SYSTEM'),
 ('ATTENDANCE_STATUS','LEAVE','Leave','Leave','ACTIVE',1,'SYSTEM'),
 ('ATTENDANCE_STATUS','HALF_DAY','Half Day','Half','ACTIVE',1,'SYSTEM'),
 ('OWNER_TYPE','SELF','Self Owned','Owned','ACTIVE',1,'SYSTEM'),
 ('OWNER_TYPE','HIRED','Hired','Hired','ACTIVE',1,'SYSTEM'),
 ('ACCOUNT_TYPE','ASSET','Asset','Asset','ACTIVE',1,'SYSTEM'),
 ('ACCOUNT_TYPE','LIABILITY','Liability','Liability','ACTIVE',1,'SYSTEM'),
 ('ACCOUNT_TYPE','EQUITY','Equity','Equity','ACTIVE',1,'SYSTEM'),
 ('ACCOUNT_TYPE','INCOME','Income','Income','ACTIVE',1,'SYSTEM'),
 ('ACCOUNT_TYPE','EXPENSE','Expense','Expense','ACTIVE',1,'SYSTEM'),
 ('DESTINATION_CITY','PERAMBALUR','Perambalur','Local','ACTIVE',1,'SYSTEM'),
 ('DESTINATION_CITY','ARIYALUR','Ariyalur','Nearby','ACTIVE',1,'SYSTEM'),
 ('DESTINATION_CITY','TRICHY','Trichy','Trichy','ACTIVE',1,'SYSTEM'),
 ('DESTINATION_CITY','THURAIYUR','Thuraiyur','Thuraiyur','ACTIVE',1,'SYSTEM'),
 ('DESTINATION_CITY','NAMAKKAL','Namakkal','Namakkal','ACTIVE',1,'SYSTEM'),
 ('DESTINATION_CITY','SALEM','Salem','Salem','ACTIVE',1,'SYSTEM'),
 ('DESTINATION_CITY','KARUR','Karur','Karur','ACTIVE',1,'SYSTEM'),
 ('DESTINATION_CITY','THANJAVUR','Thanjavur','Thanjavur','ACTIVE',1,'SYSTEM'),
 ('NOTIFICATION_TYPE','BOOKING','Booking Alert','Booking','ACTIVE',1,'SYSTEM'),
 ('NOTIFICATION_TYPE','TRIP','Trip Alert','Trip','ACTIVE',1,'SYSTEM'),
 ('NOTIFICATION_TYPE','PAYMENT','Payment Alert','Payment','ACTIVE',1,'SYSTEM'),
 ('NOTIFICATION_TYPE','MAINTENANCE','Maintenance Due','Fleet','ACTIVE',1,'SYSTEM'),
 ('DASHBOARD_CARD','TODAY_TRIPS','Today Trips','KPI','ACTIVE',1,'SYSTEM'),
 ('DASHBOARD_CARD','REVENUE_TODAY','Revenue Today','KPI','ACTIVE',1,'SYSTEM'),
 ('DASHBOARD_CARD','OUTSTANDING','Customer Outstanding','KPI','ACTIVE',1,'SYSTEM'),
 ('DASHBOARD_CARD','FLEET_UTIL','Fleet Utilization','KPI','ACTIVE',1,'SYSTEM'),
 ('MENU_GROUP','MASTERS','Masters','Menu','ACTIVE',1,'SYSTEM'),
 ('MENU_GROUP','OPERATIONS','Operations','Menu','ACTIVE',1,'SYSTEM'),
 ('MENU_GROUP','FINANCE','Finance','Menu','ACTIVE',1,'SYSTEM'),
 ('MENU_GROUP','ADMIN','Admin','Menu','ACTIVE',1,'SYSTEM'),
 ('REPORT_TYPE','FLEET','Fleet Report','Report','ACTIVE',1,'SYSTEM'),
 ('REPORT_TYPE','REVENUE','Revenue Report','Report','ACTIVE',1,'SYSTEM'),
 ('REPORT_TYPE','EXPENSE','Expense Report','Report','ACTIVE',1,'SYSTEM'),
 ('REPORT_TYPE','TRIP','Trip Report','Report','ACTIVE',1,'SYSTEM'),
 ('REPORT_TYPE','FUEL','Fuel Report','Report','ACTIVE',1,'SYSTEM')
ON CONFLICT (company_id, type, code) DO NOTHING;
